import type { Metadata } from 'next';
import { Rubik, Lato, Roboto } from 'next/font/google';
import './globals.css';
import { Header } from '@/layouts';

const rubik = Rubik({
	variable: '--font-rubik',
	subsets: ['latin'],
	weight: ['300', '400', '500', '700', '900'],
});

const lato = Lato({
	variable: '--font-lato',
	subsets: ['latin'],
	weight: ['100', '300', '400', '700', '900'],
});

const roboto = Roboto({
	variable: '--font-roboto',
	subsets: ['latin'],
	weight: ['100', '300', '400', '700', '900'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${rubik.variable} ${lato.variable} ${roboto.variable} antialiased`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
